on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: main
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_DIR: .
          REPOSITORY: the-leftist-library/the-leftist-library.github.io